#
# Copyright 2023 Tomshley LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, softomshley_breakground
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# @author Thomas Schena @sgoggles <https://github.com/sgoggles> | <https://gitlab.com/sgoggles>
#

image:
  name: "registry.gitlab.com/tomshley/breakground-provisioning/provisioning_terraform_with_py_dindx:0.3.0"

stages:
  - promote-build-feature-merge-request
  - validate-all
  - plan-remote-backend
  - promote-build-start
  - promote-build-release-finish
  - apply-remote-backend

validate-all:
  variables:
    # Tell docker CLI how to talk to Docker daemon.
    DOCKER_HOST: tcp://dockerdaemon:2375/
    # Use the overlayfs driver for improved performance.
    DOCKER_DRIVER: overlay2
    # Disable TLS since we're running inside local network.
    DOCKER_TLS_CERTDIR: ""
  services:
    - name: registry.gitlab.com/tomshley/breakground-provisioning/provisioning_terraform_with_py_dindx:0.3.0
      alias: dockerdaemon
  except:
    - tags
  stage: validate-all
  script:
    - source /opt/tomshley/breakground-provisioning/cicd/bin/cicd-dockers-build.sh
    - source /opt/tomshley/breakground-provisioning/cicd/bin/cicd-backends-local-validate.sh
    - source /opt/tomshley/breakground-provisioning/cicd/bin/cicd-backends-remote-validate.sh

plan-remote-backend:
  stage: plan-remote-backend
  script:
    - source /opt/tomshley/breakground-provisioning/cicd/bin/cicd-backends-remote-plan.sh

promote-build-start:
  stage: promote-build-start
  only:
    - develop
  script:
    - source /opt/tomshley/breakground-provisioning/cicd/bin/cicd-flow-release-start.sh
    - source /opt/tomshley/breakground-provisioning/cicd/bin/cicd-flow-release-publish.sh

promote-build-release-finish:
  stage: promote-build-release-finish
  only:
    - /^release\/.*$/
  script:
    - source /opt/tomshley/breakground-provisioning/cicd/bin/cicd-flow-release-finish.sh

promote-build-feature-merge-request:
  stage: promote-build-feature-merge-request
  only:
    - /^feature\/.*$/
  script:
    - source /opt/tomshley/breakground-provisioning/cicd/bin/cicd-flow-feature-gitlab-merge-request.sh

apply-remote-backend:
  only:
    - tags
  except:
    - branches
  stage: apply-remote-backend
  script:
    - source /opt/tomshley/breakground-provisioning/cicd/bin/cicd-backends-remote-plan.sh
