#
# Copyright 2023 Tomshley LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, softomshley_breakground
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# @author Thomas Schena @sgoggles <https://github.com/sgoggles> | <https://gitlab.com/sgoggles>
#

image:
  name: "registry.gitlab.com/tomshley/breakground-provisioning/provisioning_terraform:latest"

stages:
  - validate-remote-backend
  - plan-remote-backend
  - apply-remote-backend

validate-remote-backend:
  stage: validate-remote-backend
  before_script:
    - source "${CI_PROJECT_DIR}/scripts/cicd-bootstrap-gitlab.sh"
  script:
    - source "${CI_PROJECT_DIR}/scripts/cicd-terraform-validate.sh"

plan-remote-backend:
  stage: plan-remote-backend
  before_script:
    - source "${CI_PROJECT_DIR}/scripts/cicd-bootstrap-gitlab.sh"
  script:
    - source "${CI_PROJECT_DIR}/scripts/cicd-terraform-plan.sh"

apply-remote-backend:
  only:
    - tags
  except:
    - branches
  stage: apply-remote-backend
  before_script:
    - source "${CI_PROJECT_DIR}/scripts/cicd-bootstrap-gitlab.sh"
  script:
    - source "${CI_PROJECT_DIR}/scripts/cicd-terraform-plan-apply.sh"