#
# Copyright 2023 Tomshley LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, softomshley_breakground
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# @author Thomas Schena @sgoggles <https://github.com/sgoggles> | <https://gitlab.com/sgoggles>
#

include:
  - '/templates/.flow-generic.yml'

.flow-generic-artifacts:
  artifacts:
    name: "terraform/backends/remote/.tfstate.plan"
    paths:
      - "terraform/backends/remote/.tfstate.plan"
      - "terraform/backends/remote/.tfstate.plan.txt"
      - "terraform/backends/remote/.tfstate.plan.changes"
    reports:
      terraform:
        - "terraform/backends/remote/.tfstate.plan.json"

.flow-generic-test-breakground:
  script:
    - source /opt/tomshley/breakground-provisioning/cicd/bin/cicd-backends-local-validate.sh

.flow-generic-test-containers:
  script:
    - if [ -n "${CI_COMMIT_TAG-}" ]; then export TOMSHLEY_DOCKERS_BUILD_REF="${CI_COMMIT_REF_SLUG}"; elif [ -n "${CI_COMMIT_REF_SLUG-}" ]; then export TOMSHLEY_DOCKERS_BUILD_REF=${CI_COMMIT_REF_SLUG}-${CI_COMMIT_SHORT_SHA}; fi
    - echo "CI_COMMIT_TAG (Test Containers) = ${CI_COMMIT_TAG}"
    - echo "TOMSHLEY_DOCKERS_BUILD_REF (Test Containers) = ${TOMSHLEY_DOCKERS_BUILD_REF}"
    - source /opt/tomshley/breakground-provisioning/cicd/bin/cicd-dockers-build.sh

.flow-generic-test-provisioning:
  script:
    - source /opt/tomshley/breakground-provisioning/cicd/bin/cicd-backends-remote-validate.sh

.flow-generic-build-containers:
  script:
    - if [ -n "${CI_COMMIT_TAG-}" ]; then export TOMSHLEY_DOCKERS_BUILD_REF="${CI_COMMIT_REF_SLUG}"; elif [ -n "${CI_COMMIT_REF_SLUG-}" ]; then export TOMSHLEY_DOCKERS_BUILD_REF=${CI_COMMIT_REF_SLUG}-${CI_COMMIT_SHORT_SHA}; fi
    - echo "CI_COMMIT_TAG (Build Containers) = ${CI_COMMIT_TAG}"
    - echo "TOMSHLEY_DOCKERS_BUILD_REF (Build Containers) = ${TOMSHLEY_DOCKERS_BUILD_REF}"
    - source /opt/tomshley/breakground-provisioning/cicd/bin/cicd-dockers-build-push.sh

.flow-generic-build-provisioning:
  script:
    - source /opt/tomshley/breakground-provisioning/cicd/bin/cicd-backends-remote-plan-no-lock.sh

.flow-generic-deploy-containers:
  script:
     - if [ -n "${CI_COMMIT_TAG-}" ]; then export TOMSHLEY_DOCKERS_BUILD_REF="${CI_COMMIT_REF_SLUG}"; elif [ -n "${CI_COMMIT_REF_SLUG-}" ]; then export TOMSHLEY_DOCKERS_BUILD_REF=${CI_COMMIT_REF_SLUG}-${CI_COMMIT_SHORT_SHA}; fi
     - echo "CI_COMMIT_TAG (Deploy Containers) = ${CI_COMMIT_TAG}"
     - echo "TOMSHLEY_DOCKERS_BUILD_REF  (Deploy Containers) = ${TOMSHLEY_DOCKERS_BUILD_REF}"
     - source /opt/tomshley/breakground-provisioning/cicd/bin/cicd-dockers-build-push.sh

.flow-generic-deploy-provisioning:
  script:
    - source /opt/tomshley/breakground-provisioning/cicd/bin/cicd-backends-remote-plan-apply.sh
