#
# Copyright 2023 Tomshley LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, softomshley_breakground
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# @author Thomas Schena @sgoggles <https://github.com/sgoggles> | <https://gitlab.com/sgoggles>
#

image:
  name: "registry.gitlab.com/tomshley/breakground-provisioning/provisioning_terraform_with_py:latest"

.artifacts.tfstate.plan:
  artifacts:
    name: "terraform/backends/remote/.tfstate.plan"
    paths:
      - "terraform/backends/remote/.tfstate.plan"
      - "terraform/backends/remote/.tfstate.plan.txt"
      - "terraform/backends/remote/.tfstate.plan.changes"
    reports:
      terraform:
        - "terraform/backends/remote/.tfstate.plan.json"

#
#     - promote-build-feature-merge-request
#     - test
#     - build
#     - promote-build-start
#     - promote-build-release-publish
#     - promote-build-release-finish
#     - deploy
stages:
  - .pre
  - test
  - build
  - deploy
  - .post

test:
  extends: .artifacts.tfstate.plan
  tags:
    - saas-linux-xlarge-amd64
  services:
    - name: docker:24.0.5-dind-alpine3.18
      alias: dockerdaemon
  except:
    - tags
  stage: test
  script:
    - source /opt/tomshley/breakground-provisioning/cicd/bin/cicd-dockers-build.sh
    - source /opt/tomshley/breakground-provisioning/cicd/bin/cicd-backends-local-validate.sh
    - source /opt/tomshley/breakground-provisioning/cicd/bin/cicd-backends-remote-validate.sh
  artifacts:
    expire_in: 8 hours

build:
  extends: .artifacts.tfstate.plan
  stage: build
  services:
    - name: docker:24.0.5-dind-alpine3.18
      alias: dockerdaemon
  script:
    - source /opt/tomshley/breakground-provisioning/cicd/bin/cicd-dockers-build.sh
    - source /opt/tomshley/breakground-provisioning/cicd/bin/cicd-backends-remote-plan-no-lock.sh
  artifacts:
    expire_in: 8 hours

job-flow-release-start:
  stage: .post
  tags:
    - saas-linux-xlarge-amd64
  services:
    - name: docker:24.0.5-dind-alpine3.18
      alias: dockerdaemon
  only:
    - develop
  script:
    - source /opt/tomshley/breakground-provisioning/cicd/bin/cicd-flow-release-start.sh
  when: manual

job-flow-release-publish:
  stage: deploy
  only:
    - /^release\/.*$/
  script:
    - source /opt/tomshley/breakground-provisioning/cicd/bin/cicd-flow-release-publish.sh

job-flow-release-finish:
  stage: .post
  only:
    - /^release\/.*$/
  script:
    - source /opt/tomshley/breakground-provisioning/cicd/bin/cicd-flow-release-finish.sh

job-flow-feature-start:
  stage: .pre
  only:
    - /^feature\/.*$/
    - pushes
  script:
    - source /opt/tomshley/breakground-provisioning/cicd/bin/cicd-flow-feature-gitlab-merge-request.sh

deploy:
  extends: .artifacts.tfstate.plan
  environment: production
  tags:
    - saas-linux-2xlarge-amd64
  services:
    - name: docker:24.0.5-dind-alpine3.18
      alias: dockerdaemon
  only:
    - tags
  except:
    - branches
  stage: deploy
  script:
    - source /opt/tomshley/breakground-provisioning/cicd/bin/cicd-dockers-build-push.sh
    - source /opt/tomshley/breakground-provisioning/cicd/bin/cicd-backends-remote-plan-apply.sh
